version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: lakehouse_postgres
    environment:
      POSTGRES_DB: lakehouse_modeling
      POSTGRES_USER: lakehouse_user
      POSTGRES_PASSWORD: lakehouse_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - lakehouse_network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: lakehouse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lakehouse_network
    restart: unless-stopped

  # Elasticsearch搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: lakehouse_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lakehouse_network
    restart: unless-stopped

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: lakehouse_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: lakehouse_user
      RABBITMQ_DEFAULT_PASS: lakehouse_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lakehouse_network
    restart: unless-stopped

  # Kibana (Elasticsearch管理界面)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: lakehouse_kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - lakehouse_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  rabbitmq_data:

networks:
  lakehouse_network:
    driver: bridge

