version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lakehouse_postgres
    environment:
      POSTGRES_DB: lakehouse_modeling
      POSTGRES_USER: lakehouse_user
      POSTGRES_PASSWORD: lakehouse_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lakehouse_user -d lakehouse_modeling"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
