server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: lakehouse-modeling-tool
  
  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/lakehouse_modeling
    username: lakehouse_user
    password: ENC(lakehouse_pass)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Elasticsearch配置
  elasticsearch:
    uris: http://localhost:9200
    username: 
    password: 
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # 安全配置
  security:
    jwt:
      secret: ENC(lakehouse_jwt_secret_key_2024)
      expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    com.lakehouse: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/lakehouse-modeling.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 自定义配置
lakehouse:
  # 数据源连接配置
  datasource:
    # 连接测试超时时间
    connection-test-timeout: 10000
    # 元数据同步间隔（分钟）
    sync-interval: 60
    # 支持的数据源类型
    supported-types:
      - mysql
      - postgresql
      - hive
      - clickhouse
  
  # DDL解析配置
  ddl:
    # 最大DDL长度
    max-length: 100000
    # 解析超时时间
    parse-timeout: 30000
  
  # 建模配置
  modeling:
    # 自动保存间隔（秒）
    auto-save-interval: 2
    # 最大字段数量
    max-fields: 1000
  
  # 血缘关系配置
  lineage:
    # 最大血缘深度
    max-depth: 10
    # 血缘计算超时时间
    calculation-timeout: 60000
  
  # 搜索配置
  search:
    # 搜索结果最大数量
    max-results: 1000
    # 搜索超时时间
    search-timeout: 10000

# 加密配置
jasypt:
  encryptor:
    password: lakehouse_encryption_key_2024
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

